### ISSUE TITLE
First Person Aiming FOV resets to default after taking damage

### ISSUE THREAD

**Issue by Sparktimus** [CamxxCore/ExtendedCameraSettings#1]
It's probably to do with the Casino Update but the first person regular hip fire FOV resets after taking damage, and I don't know if it's because of the damage indicator or just a variable changing. It goes back to normal after you cycle through the camera modes in game but it happens every time you receive any damage

**Comment by Naworm** [comment]
It seems fixed on latest version

**Comment by Naworm** [comment]
@CamxxCore I guess you can close the issue
