### ISSUE TITLE
Fails to execute under Windows 8.1 (7 possibly too)

### ISSUE THREAD

**Issue by Flufiakojot** [CamxxCore/ExtendedCameraSettings#11]
![image](https://user-images.githubusercontent.com/89755606/175315924-cd11a9e9-6c78-4c45-96a8-95707bc0f8e8.png)

The rest of my mods work fine on 8.1. Extended camera did work on Windows 10 and 11 with the same mods.

**Comment by CamxxCore** [comment]
Install all Visual Studio C++ runtimes.

**Comment by Flufiakojot** [comment]
> Install all Visual Studio C++ runtimes.

![image](https://user-images.githubusercontent.com/89755606/175546952-a1ac83c0-6ca7-455e-9124-273f2f8e9ad6.png)
Already had them installed, however, I have noticed that it first applies only first-person FOV then crashes,

**Comment by Flufiakojot** [comment]
The problem magically solved after installing a different build of Windows 8.1. Closing this now :)
