### ISSUE TITLE
Russian localization likely crashes or causes undefined behaviour

### ISSUE THREAD

**Issue by CamxxCore** [CamxxCore/ExtendedCameraSettings#4]
Array contains 29 localized strings when 31 are required

**Comment by CamxxCore** [comment]
@Des98 Can you check the array to make sure all 31 strings are included?

**Comment by longaru** [comment]
Try this edit of Des98 version :
`static LPCTSTR ru_ru[] {
    u8"Поле обзора камеры (первое лицо)",
    u8"Всегда отображать прицел (первое лицо)",
    u8"Минимальный угол наклона камеры (первое лицо)",
    u8"Максимальный угол наклона камеры (первое лицо)",
    u8"Поле обзора камеры при прицеливании (первое лицо)",
    u8"Поле обзора камеры (третье лицо)",
    u8"Автоцентровка камеры (третье лицо)",
    u8"Отношение камеры по горизонтали (третье лицо)",
    u8"Отношение камеры по вертикали (третье лицо)",
    u8"Дистанция камеры пешком (третье лицо)",
    u8"Дрожание камеры во время бега (третье лицо)",
    u8"Минимальный угол наклона камеры (третье лицо)",
    u8"Максимальный угол наклона камеры (третье лицо)",
    u8"Поле обзора во время прицеливания (третье лицо)",
    u8"Отношение камеры во время стрельбы по горизонтали (третье лицо)",
    u8"Дистанция камеры во время стрельбы (третье лицо)",
    u8"Поле обзора камеры в транспорте (первое лицо)",
    u8"Отношение камеры в автомобиле по вертикали (первое лицо)",
    u8"Не переключать камеру, когда транспорт в воде (первое лицо)",
    u8"Не переключать камеру, когда транспорт уничтожен (первое лицо)",
    u8"Минимальный угол наклона камеры в транспорте (первое лицо)",
    u8"Максимальный угол наклона камеры в транспорте (первое лицо)",
    u8"Поле обзора камеры в транспорте (третье лицо)",
    u8"Минимальный угол наклона камеры в транспорте (третье лицо)",
    u8"Максимальный угол наклона камеры в транспорте (третье лицо)",
    u8"Автоцентровка камеры в транспорте во время езды (третье лицо)",
    u8"Дистанция камеры в транспорте (третье лицо)",
    u8"Отдаление камеры в транспорте на высоких скоростях (третье лицо)",
    u8"Масштабирование высоты камеры в транспорте (третье лицо)",
    u8"Отношение камеры в транспорте по горизонтали (третье лицо)",
    u8"Дрожание камеры в транспорте на высоких скоростях (третье лицо)"
};`

And this is like ENG style words ( first letter is big ) :
`static LPCTSTR ru_ru[] {
    u8"Поле Обзора Камеры (Первое Лицо)",
    u8"Всегда Отображать Прицел (Первое Лицо)",
    u8"Минимальный Угол Наклона Камеры (Первое Лицо)",
    u8"Максимальный Угол Наклона Камеры (Первое Лицо)",
    u8"Поле Обзора Камеры при Прицеливании (Первое Лицо)",
    u8"Поле Обзора Камеры (Третье Лицо)",
    u8"Автоцентровка Камеры (Третье Лицо)",
    u8"Отношение Камеры по Горизонтали (Третье Лицо)",
    u8"Отношение Камеры по Вертикали (Третье Лицо)",
    u8"Дистанция Камеры Пешком (Третье Лицо)",
    u8"Дрожание Камеры во Время Бега (Третье Лицо)",
    u8"Минимальный Угол Наклона Камеры (Третье Лицо)",
    u8"Максимальный Угол Наклона Камеры (Третье Лицо)",
    u8"Поле Обзора во Время Прицеливания (Третье Лицо)",
    u8"Отношение Камеры во Время Стрельбы по Горизонтали (Третье Лицо)",
    u8"Дистанция Камеры во Время Стрельбы (Третье Лицо)",
    u8"Поле Обзора Камеры в Транспорте (Первое Лицо)",
    u8"Отношение Камеры в Транспорте по Вертикали (Первое Лицо)",
    u8"Не Переключать Камеру, Когда Транспорт в Воде (Первое Лицо)",
    u8"Не Переключать Камеру, Когда Транспорт Уничтожен (Первое Лицо)",
    u8"Минимальный Угол Наклона Камеры в Транспорте (Первое Лицо)",
    u8"Максимальный Угол Наклона Камеры в Транспорте (Первое Лицо)",
    u8"Поле Обзора Камеры в Транспорте (Третье Лицо)",
    u8"Минимальный Угол Наклона Камеры в Транспорте (Третье Лицо)",
    u8"Максимальный Угол Наклона Камеры в Транспорте (Третье Лицо)",
    u8"Автоцентровка Камеры в Транспорте во Время Езды (Третье Лицо)",
    u8"Дистанция Камеры в Транспорте (Третье Лицо)",
    u8"Отдаление Камеры в Транспорте на Высоких Скоростях (Третье Лицо)",
    u8"Высота Камеры в Транспорте (Третье Лицо)",
    u8"Отношение Камеры в Транспорте по Горизонтали (Третье Лицо)",
    u8"Дрожание Камеры в Транспорте на Высоких Скоростях (Третье Лицо)"
};`

Take what You seems better  ; )

**Comment by CamxxCore** [comment]
@longaru Hopefully resolved with this change, thanks for the help 👍 I will bundle this fix with a future release that includes a few more bug fixes I'm wokring on.
