### ISSUE TITLE
Sensitivity is affected by FOV

### ISSUE THREAD

**Issue by Naworm** [CamxxCore/ExtendedCameraSettings#5]
Hello, you mod is really great thanks for it (even if he is pretty hard to configure the first time).

Actually, when you change FOV the sensitivity will be affected with some ratio (maybe 1.33). It's like the old FPS games. 
For the same mouse movement you will go further every time you increase the FOV.
So you have to stick to an FOV, or, your mouse movements will be hazardous.

May you plan to implement an option for linear FOV ratio, like most of recent FPS games ?

**Comment by CamxxCore** [comment]
I can't promise this will be added, the mod simply modifies the camera parameters in memory so this logic is likely baked into the game itself.
