### ISSUE TITLE
Mod broken by Contract DLC please update :)

### ISSUE THREAD

**Issue by AmazyCrazy** [CamxxCore/ExtendedCameraSettings#7]
@Camxxcore this mod has been broken by the contracts dlc could you please update it? many people have asked in the comments section of the mod on gta5-mods.com

Thanks :)

**Comment by CamxxCore** [comment]
Resolved https://github.com/CamxxCore/ExtendedCameraSettings/commit/1d4e89da524388d286b452c338638614baf87a39
