### ISSUE TITLE
Not compatible with latest update build 2245 the contract update

### ISSUE THREAD

**Issue by JBuzz826** [CamxxCore/ExtendedCameraSettings#8]
This scripthook script is not compatible with the latest build 2245. Looking at the code and main file shows older previous versions.

**Comment by JBuzz826** [comment]
[main.h.zip](https://github.com/CamxxCore/ExtendedCameraSettings/files/7809631/main.h.zip)

Can you verify if this might fix?

**Comment by AmazyCrazy** [comment]
@JBuzz826 what is that file for?

**Comment by JBuzz826** [comment]
> @JBuzz826 what is that file for?

@AmazyCrazy It is one of the main files which reads the game version for steam and epic. 

I tried to see if I can add in the previous builds and current build 2245. I think this is what the issue might be? R* did something funky with the update, which broke this script. 

I'd like to help get this compatible with the current version of GTAV build 2245. I'm hoping @CamxxCore might see these and hopefully can figure it out.

**Comment by CamxxCore** [comment]
Resolved https://github.com/CamxxCore/ExtendedCameraSettings/commit/1d4e89da524388d286b452c338638614baf87a39
